{"name": "test_valid_authentication", "status": "failed", "statusDetails": {"message": "AssertionError: Authentication failed for public repo\nassert 401 == 200\n +  where 401 = <Response [401]>.status_code", "trace": "def test_valid_authentication():\n        \"\"\"Step 1: Test valid API authentication by accessing a public repository.\"\"\"\n        print(\"\\nðŸ”¹ Running: test_valid_authentication\")\n        response = api.get_repository(OWNER, PUBLIC_REPO_NAME)\n>       assert response.status_code == 200, \"Authentication failed for public repo\"\nE       AssertionError: Authentication failed for public repo\nE       assert 401 == 200\nE        +  where 401 = <Response [401]>.status_code\n\ntests\\api_tests\\test_authentication_api.py:25: AssertionError"}, "description": "Step 1: Test valid API authentication by accessing a public repository.", "attachments": [{"name": "stdout", "source": "d56a2349-abe4-445a-818a-108b4e2ce4aa-attachment.txt", "type": "text/plain"}], "start": 1742175256975, "stop": 1742175257253, "uuid": "e044916a-d4ad-4f8d-828c-6a31cbf0ebc2", "historyId": "4074888c26d0519cd1c8ab3f6b3e22aa", "testCaseId": "4074888c26d0519cd1c8ab3f6b3e22aa", "fullName": "tests.api_tests.test_authentication_api#test_valid_authentication", "labels": [{"name": "parentSuite", "value": "tests.api_tests"}, {"name": "suite", "value": "test_authentication_api"}, {"name": "host", "value": "BHUVANSPC"}, {"name": "thread", "value": "9344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api_tests.test_authentication_api"}]}